### ISSUE TITLE
多语言切换只显示中文

### ISSUE THREAD

**Issue by dianzinidaye** [ak-ing/SkinPlugin#4]
换肤之后只支持中文,切换不到其他语言

**Comment by ak-ing** [comment]
请问如何复现？

**Comment by dianzinidaye** [comment]
使用
`        LocaleListCompat appLocale = LocaleListCompat.forLanguageTags(string);
         AppCompatDelegate.setApplicationLocales(appLocale);`
进行国际化多语言切换,切换语言失败,用到资源的文字还是中文,恢复默认主题就可以切换语言

**Comment by ak-ing** [comment]
你的多语言资源放在App内还是皮肤包内？
如果你的string资源在App内，检查皮肤包中是否存在同名的string资源，删除皮肤包中同名的string资源即可

**Comment by ak-ing** [comment]
如果你的多国语言资源集成在皮肤包内，而非App内，请查看[SkinPlugin-v1.0.1](https://github.com/ak-ing/SkinPlugin/releases/tag/SkinPlugin-v1.0.1)
